import { Category } from '../../app/model/category-model'

export const allCategories: Category[] = [
  { name: 'Fragmenty ksiażek', id: 0, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'Fragmenty piosenek', id: 1, checkbox: false, class: ' bg-secondary bg-gradient' },
  { name: 'Wypisz kraje lub stolice', id: 2, checkbox: false, class: 'bg-success bg-gradient' },
  { name: 'Klubowa Historia', id: 3, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Klubowe herby', id: 4, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Filmy - opis', id: 5, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Seriale - opis', id: 6, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Gra - opis', id: 7, checkbox: false, class: 'bg-info bg-gradient' },
  { name: 'Miasto - Województwo', id: 8, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'Stadiony świata', id: 9, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Przysłowia', id: 10, checkbox: false, class: 'bg-warning bg-gradient' },
  { name: 'Historia', id: 11, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'Rozpoznaj osobe ze zdjęcia', id: 12, checkbox: false, class: ' bg-secondary bg-gradient' },
  { name: 'Rozpoznaj budowle ze zdjęcia', id: 13, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'W jakim filmie zagrała taka obsada?', id: 14, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'W jakim serialu zagrała taka obsada?', id: 15, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Jaka to melodia?', id: 16, checkbox: false, class: ' bg-secondary bg-gradient' },
  { name: 'Czołówka serialu', id: 17, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Pierwiastki', id: 18, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'Biologia', id: 19, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'Bogowie', id: 20, checkbox: false, class: 'bg-dark bg-gradient' },
  { name: 'Rozpoznaj artystę po tytułach piosenek', id: 21, checkbox: false, class: ' bg-secondary bg-gradient' },
  { name: 'Państwo po miastach', id: 22, checkbox: false, class: 'bg-success bg-gradient' },
  { name: 'Rozpoznaj film po bohaterach', id: 23, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Rozpoznaj serial po bohaterach', id: 24, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Reżyser po filmach', id: 25, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Rozpoznaj impreze po piosence', id: 26, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Zawodnik klub reprezentacja', id: 27, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Pytanie wielokrotnego wyboru', id: 28, checkbox: false, class: 'bg-warning bg-gradient' },
  { name: 'Z jakiego kraju jest ta flaga?', id: 29, checkbox: false, class: 'bg-success bg-gradient' },
  { name: 'Stolice krajów?', id: 30, checkbox: false, class: 'bg-success bg-gradient' },
  { name: 'Familiada', id: 31, checkbox: false, class: 'bg-warning bg-gradient' },
  { name: 'Był taki mecz', id: 32, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Wypisywanie róznych wspólnych', id: 33, checkbox: false, class: 'bg-warning bg-gradient' },
  { name: 'Wypisywanie róznych wspólnych - piłka nożna', id: 34, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Piłkarskie kółko i krzyżyk', id: 35, checkbox: false, class: 'bg-danger bg-gradient' },
  { name: 'Aktorskie kółko i krzyżyk', id: 36, checkbox: false, class: 'bg-primary bg-gradient' },
  { name: 'Jakie to logo?', id: 37, checkbox: false, class: 'bg-warning bg-gradient' },
]
